blog/urls.py
'''
    seductiveblog - an open source blogging platform
    Copyright (C) 2018, Simon Connah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''
from django.urls import path
from . import views

urlpatterns = [
    # general URLs
    path('contact-us/', views.ContactUsView.as_view(), name='contact_us'),
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('terms-of-service/', views.TermsOfServiceView.as_view(), name='terms-of-service'),

    # general control panel URLs
    path('control-panel/', views.ControlPanelHome.as_view(), name='control_panel'),

    # user facing blog article URLs
    path('article/<int:pk>/<slug:article_slug>/', views.BlogPostDetailView.as_view(),
         name='blog_article_detail'),
    path('article/list/', views.BlogPostListView.as_view(), name='blog_article_list'),

    # blog article control panel URLs
    path('control-panel/articles/', views.ControlPanelBlogPostHome.as_view(), name='blog_article_control_panel_home'),
    path('control-panel/create-post/', views.BlogPostCreateView.as_view(), name='blog_article_create'),
    path('control-panel/update-post/<int:pk>/', views.BlogPostUpdateView.as_view(), name='blog_article_update'),
    path('control-panel/delete-post/<int:pk>/', views.BlogPostDeleteView.as_view(), name='blog_article_delete'),

    # user facing blog category URLs
    path('category/<int:pk>/<slug:category_slug>/', views.BlogCategoryDetailView.as_view(),
         name='blog_category_detail'),
    path('category/list/', views.BlogCategoryListView.as_view(), name='blog_category_list'),

    # blog category control panel URLs
    path('control-panel/categories/', views.ControlPanelBlogCategoryHome.as_view(),
         name='blog_category_control_panel_home'),
    path('control-panel/create-category/', views.BlogCategoryCreateView.as_view(), name='blog_category_create'),
    path('control-panel/update-category/<int:pk>/', views.BlogCategoryUpdateView.as_view(),
         name='blog_category_update'),
    path('control-panel/delete-category/<int:pk>/', views.BlogCategoryDeleteView.as_view(),
         name='blog_category_delete'),

    # user facing blog tag URLs
    path('tag/<int:pk>/<slug:tag_slug>/', views.BlogTagDetailView.as_view(), name='blog_tag_detail'),
    path('tag/list/', views.BlogTagListView.as_view(), name='blog_tag_list'),

    # blog tag control panel URLs
    path('control-panel/tags/', views.ControlPanelBlogTagHome.as_view(), name='blog_tag_control_panel_home'),
    path('control-panel/create-tag/', views.BlogTagCreateView.as_view(), name='blog_tag_create'),
    path('control-panel/update-tag/<int:pk>/', views.BlogTagUpdateView.as_view(), name='blog_tag_update'),
    path('control-panel/delete-tag/<int:pk>/', views.BlogTagDeleteView.as_view(), name='blog_tag_delete'),

    # user facing blog page URLs
    path('page/<int:pk>/<slug:page_slug>/', views.BlogPageDetailView.as_view(), name='blog_page_detail'),
    path('page/list/', views.BlogPageListView.as_view(), name='blog_page_list'),

    # blog page control panel URLs
    path('control-panel/pages/', views.ControlPanelBlogPageHome.as_view(), name='blog_page_control_panel_home'),
    path('control-panel/create-page/', views.BlogPageCreateView.as_view(), name='blog_page_create'),
    path('control-panel/update-page/<int:pk>/', views.BlogPageUpdateView.as_view(), name='blog_page_update'),
    path('control-panel/delete-page/<int:pk>/', views.BlogPageDeleteView.as_view(), name='blog_page_delete'),

    # blog comment control panel URLs
    path('control-panel/comments/', views.ControlPanelBlogCommentHome.as_view(),
         name='blog_comment_control_panel_home'),
    path('control-panel/comment/list/<int:article_id>/', views.ControlPanelBlogCommentListByArticle.as_view(),
         name='blog_comment_list_by_article_control_panel'),
    path('control-panel/comment/list/reported/', views.ControlPanelBlogCommentListReported.as_view(),
         name='blog_comment_list_reported_control_panel'),
    path('control-panel/delete-comment/<int:pk>/', views.BlogCommentDeleteView.as_view(), name='blog_comment_delete'),
    path('control-panel/update-comment/<int:pk>/', views.BlogCommentUpdateView.as_view(), name='blog_comment_update'),

    # user facing comment URLs
    path('comment/<int:pk>/', views.BlogCommentDetailView.as_view(), name='blog_comment_detail'),
    path('comment/list/<int:article_id>/', views.BlogCommentListView.as_view(), name='blog_comment_list_by_article'),
    path('comment/create-comment/<int:article_id>/', views.BlogCommentCreateView.as_view(), name='blog_comment_create'),

    # user facing comment voting URLs
    path('comment/like/<int:comment_id>/', views.blog_comment_like, name='blog_comment_like'),
    path('comment/dislike/<int:comment_id>/', views.blog_comment_dislike, name='blog_comment_dislike'),
    path('comment/report/<int:comment_id>/', views.blog_report_comment, name='blog_comment_report'),
    path('comment/<int:comment_id>/success/', views.blog_comment_vote_success, name='blog_comment_vote_success'),
    path('comment/<int:comment_id>/fail/', views.blog_comment_vote_fail, name='blog_comment_vote_fail'),
]

seductive/urls.py
"""seductive URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from blog.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('usercp.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
'''
    seductiveblog - an open source blogging platform
    Copyright (C) 2018, Simon Connah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import Permission
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext as _
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from guardian.shortcuts import assign_perm
from images.models import Image


class BlogPost(models.Model):
    title = models.TextField(verbose_name=_('Blog Title'))
    slug = models.SlugField()
    category = models.ForeignKey('BlogCategory', on_delete=models.CASCADE, verbose_name=_('The Category for the Post'),
                                 blank=True, null=True)
    tags = models.ManyToManyField('BlogTag', verbose_name=_('Tags Associated with the Post'), blank=True)
    # the short description is designed to be a shorter version of the blog post if the owner does not want to display
    # the full post on the front page - works well when a front page image is also specified
    short_content = models.TextField(verbose_name=_('Blog Extract'))
    long_content = models.TextField(verbose_name=_('Blog Post'))
    meta_description = models.TextField(verbose_name=_('Meta Description'))
    date_posted = models.DateTimeField(auto_now_add=True, verbose_name=_('Date Posted'))
    date_updated = models.DateTimeField(auto_now=True, verbose_name=_('Date Updated'))
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('Author'))
    front_page_image = models.ForeignKey(Image, on_delete=models.CASCADE, verbose_name=_('Front Page Image'),
                                         blank=True, null=True)
    num_comments = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_article_detail', args=[str(self.id), self.slug])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = _('Blog Posts')
        verbose_name = _('Blog Post')
        get_latest_by = 'date_posted'


class BlogCategory(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                              verbose_name=_('The creator of the category'))
    name = models.TextField(verbose_name=_('Category Name'), unique=True)
    slug = models.SlugField()
    description = models.TextField(verbose_name=_('Category Description'), blank=True)
    meta_description = models.TextField(verbose_name=_('Meta Description'), blank=True)
    use_no_follow = models.BooleanField(default=True, verbose_name=_('Whether to make the Category no follow'))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_category_detail', args=[str(self.id), self.slug])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('Blog Categories')
        verbose_name = _('Blog Category')


class BlogTag(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                              verbose_name=_('The creator of the tag'))
    name = models.TextField(verbose_name=_('Tag Name'), unique=True)
    slug = models.SlugField()
    description = models.TextField(verbose_name=_('Tag Description'), blank=True)
    meta_description = models.TextField(verbose_name=_('Meta Description'), blank=True)
    use_no_follow = models.BooleanField(default=True, verbose_name=_('Whether to make the Tag no follow'))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_tag_detail', args=[str(self.id), self.slug])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('Blog Tags')
        verbose_name = _('Blog Tag')


class BlogPage(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('Author of the page'))
    title = models.TextField(verbose_name=_('Title of the page'), unique=True)
    slug = models.SlugField()
    content = models.TextField(verbose_name=_('Page content'))
    meta_description = models.TextField(verbose_name=_('Meta Description'), blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_page_detail', args=[str(self.id), self.slug])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = _('Blog Pages')
        verbose_name = _('Blog Page')


class BlogComment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                               verbose_name=_('Author of the comment'), blank=True, null=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE,
                                       verbose_name=_('The parent comment to the current one'), null=True, blank=True)
    title = models.TextField(verbose_name=_('Title of the comment'))
    slug = models.SlugField()
    content = models.TextField(verbose_name=_('The comment'))
    date_posted = models.DateTimeField(auto_now_add=True, verbose_name=_('Date comment posted'))
    date_updated = models.DateTimeField(auto_now=True, verbose_name=_('Date comment updated'))
    positive_votes = models.PositiveIntegerField(default=0)
    negative_votes = models.PositiveIntegerField(default=0)
    flagged_for_review = models.BooleanField(default=False)
    article_commented_on = models.ForeignKey('BlogPost', verbose_name=_('The article the comment is about'),
                                             on_delete=models.CASCADE)
    users_who_like_comment = ArrayField(models.TextField(), null=True, blank=True)
    users_who_dislike_comment = ArrayField(models.TextField(), null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_comment_detail', args=[str(self.id), self.slug])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = _('Blog Comments')
        verbose_name = _('Blog Comment')

# Django signals for blog app models


@receiver(pre_save, sender=BlogPost)
def blog_post_pre_save_perm_check(sender, **kwargs):
    user_model = get_user_model()
    author_user = get_object_or_404(user_model, pk=kwargs['instance'].author.id)
    if not author_user.has_perm('blog.add_blogpost'):
        # the user is not allowed to make blog posts
        raise PermissionDenied
    elif not author_user.has_perm('blog.change_blogpost') and kwargs['instance'].id:
        # the user is not allowed to change a blog post that already exists
        raise PermissionDenied


@receiver(post_save, sender=BlogPost)
def blog_post_post_save_assign_perms(sender, **kwargs):
    user_model = get_user_model()
    author_user = get_object_or_404(user_model, pk=kwargs['instance'].author.id)

    # assign permissions to the author of the blog post because they will need to maintain it in the future
    # this only assigns permissions to the author of the blog post itself - other users will be unable to edit
    # or delete it unless they are a superuser or have been given permission directly by someone else
    if not author_user.has_perm('blog.change_blogpost'):
        assign_perm('blog.change_blogpost', author_user, kwargs['instance'])
    if not author_user.has_perm('blog.delete_blogpost'):
        assign_perm('blog.delete_blogpost', author_user, kwargs['instance'])


@receiver(pre_save, sender=BlogComment)
def blog_comment_pre_save_perm_check(sender, **kwargs):
    user_model = get_user_model()
    if kwargs['instance'].author.id is not None:
        author_user = get_object_or_404(user_model, pk=kwargs['instance'].author.id)
        # TODO: We should make sure that all users have the add comment permission
        if not author_user.has_perm('blog.add_blogcomment'):
            raise PermissionDenied
        if not author_user.has_perm('blog.change_blogcomment'):
            raise PermissionDenied
    else:
        try:
            comment = BlogComment.objects.get(pk=kwargs['instance'].id)
        except BlogComment.DoesNotExist:
            return
        raise PermissionDenied


@receiver(pre_save, sender=BlogComment)
def blog_comment_post_save_author_cant_comment(sender, **kwargs):
    user_model = get_user_model()
    if kwargs['instance'].author.id is not None:

blog/templates/blog/cp/category_home.html
{% extends "blog/cp/base.html" %}
{% comment %}
    seductiveblog - an open source blogging platform
    Copyright (C) 2018, Simon Connah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load i18n %}

{% block title %}
    {% trans "Article Control Panel" %}
{% endblock %}

{% block header %}
    <h1>{% trans "Article Control Panel" %}</h1>
{% endblock %}

{% block main_body %}
    {% if user.is_authenticated and perms.blog.add_blogpost %}
        {% url "blog_category_create" as category_create %}
        {% blocktrans %}
            <p>
                <a href="{{ category_create }}"><button type="button" class="btn btn-success">Create Category</button></a>.
            </p>
        {% endblocktrans %}
    {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">{% trans "Owner" %}</th>
                <th scope="col">{% trans "Name" %}</th>
                <th scope="col">{% trans "Description" %}</th>
                {% if user.is_authenticated and perms.blog.change_blogcategory %}
                    <th scope="col">{% trans "Update" %}</th>
                {% endif %}
                {% if user.is_authenticated and perms.blog.delete_blogcategory %}
                    <th scope="col">{% trans "Delete" %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for category in object_list %}
                <tr>
                    <th scope="row"><a href="{% url "usercp_profile" category.owner.id %}">{{ category.owner.username }}</a></th>
                    <td><a href="{% url "blog_category_detail" category.id category.slug %}">{{ category.name }}</a></td>
                    <td>{{ category.description }}</td>
                    {% if user.is_authenticated and perms.blog.change_blogcategory %}
                        <td><a href="{% url "blog_category_update" category.id %}"><button type="button" class="btn btn-info">{% trans "Update" %}</button></a></td>
                    {% endif %}
                    {% if user.is_authenticated and perms.blog.delete_blogcategory %}
                        <td><a href="{% url "blog_category_delete" category.id %}"><button type="button" class="btn btn-danger">{% trans "Delete" %}</button></a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

blog/templates/blog/cp/category_update_view.html
{% extends "blog/cp/base.html" %}
{% comment %}
    seductiveblog - an open source blogging platform
    Copyright (C) 2018, Simon Connah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load i18n %}

{% block title %}
    {% trans "Update " %}{{ object }}
{% endblock %}

{% block header %}
    <h1>{% trans "Update " %}{{ object }}</h1>
{% endblock %}

{% load crispy_forms_tags %}

{% block main_body %}
    {% if user.is_authenticated and perms.blog.change_blogcategory %}
        <form action="{% url "blog_category_update" object.id %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary" value="{% trans "Update Category" %}" id="update_blog_category_button"/>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/cp/comment_home.html
{% extends "blog/cp/base.html" %}
{% comment %}
    seductiveblog - an open source blogging platform
    Copyright (C) 2018, Simon Connah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load i18n %}

{% block title %}
    {% trans "Comment Control Panel" %}
{% endblock %}

{% block header %}
    <h1>{% trans "Comment Control Panel" %}</h1>
{% endblock %}

{% block main_body %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">{% trans "Author" %}</th>
                <th scope="col">{% trans "Title" %}</th>
                {% if user.is_authenticated and perms.blog.change_blogcomment %}
                    <th scope="col">{% trans "Update" %}</th>
                {% endif %}
                {% if user.is_authenticated and perms.blog.delete_blogcomemnt %}
                    <th scope="col">{% trans "Delete" %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for comment in object_list %}
                <tr>
                    <th scope="row">
                        {% if comment.author.username %}
                            <a href="{% url "usercp_profile" comment.author.id %}">{{ comment.author.username }}</a></th>
                        {% else %}
                            <strong>{% trans "This comment was written by an Anonymous User" %}</strong></th>
                        {% endif %}
                            <td><a href="{% url "blog_comment_detail" comment.id %}">{{ comment.title }}</a></td>
                        {% if user.is_authenticated and perms.blog.change_blogcomment %}
                            {# TODO: Check if user has permissions to update specific comment #}
                            {# TODO: The current permission check does not work because it does not check if the user is allowed to edit other peoples comments #}
                            <td><a href="{% url "blog_comment_update" comment.id %}"><button type="button" class="btn btn-info">{% trans "Update" %}</button></a></td>
                        {% else %}
                            <td><button class="btn btn-info">{% trans "Can Not Update" %}</button></td>
                        {% endif %}
                        {% if user.is_authenticated and perms.blog.delete_blogcomment %}
                            <td><a href="{% url "blog_comment_delete" comment.id %}"><button type="button" class="btn btn-danger">{% trans "Delete" %}</button></a></td>
                        {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

blog/templates/blog/cp/page_home.html
{% extends "blog/cp/base.html" %}
{% comment %}
    seductiveblog - an open source blogging platform
    Copyright (C) 2018, Simon Connah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load i18n %}

{% block title %}
    {% trans "Page Control Panel" %}
{% endblock %}

{% block header %}
    <h1>{% trans "Page Control Panel" %}</h1>
{% endblock %}

{% block main_body %}
    {% if user.is_authenticated and perms.blog.add_blogpage %}
        {% url "blog_page_create" as page_create %}
        {% blocktrans %}
            <p>
                <a href="{{ page_create }}"><button type="button" class="btn btn-success">Create Page</button></a>.
            </p>
        {% endblocktrans %}
    {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">{% trans "Author" %}</th>
                <th scope="col">{% trans "Title" %}</th>
                {% if user.is_authenticated and perms.blog.change_blogpage %}
                    <th scope="col">{% trans "Update" %}</th>
                {% endif %}
                {% if user.is_authenticated and perms.blog.delete_blogpage %}
                    <th scope="col">{% trans "Delete" %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for page in object_list %}
                <tr>
                    <th scope="row"><a href="{% url "usercp_profile" page.author.id %}">{{ page.author.username }}</a></th>
                    <td><a href="{% url "blog_page_detail" page.id page.slug %}">{{ page.title }}</a></td>
                    {% if user.is_authenticated and perms.blog.change_blogpost %}
                        <td><a href="{% url "blog_page_update" page.id %}"><button type="button" class="btn btn-info">{% trans "Update" %}</button></a></td>
                    {% endif %}
                    {% if user.is_authenticated and perms.blog.delete_blogpost %}
                        <td><a href="{% url "blog_page_delete" page.id %}"><button type="button" class="btn btn-danger">{% trans "Delete" %}</button></a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

blog/templates/blog/cp/tag_home.html
{% extends "blog/cp/base.html" %}
{% comment %}
    seductiveblog - an open source blogging platform
    Copyright (C) 2018, Simon Connah

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}

{% load i18n %}

{% block title %}
    {% trans "Tag Control Panel" %}
{% endblock %}

{% block header %}
    <h1>{% trans "Tag Control Panel" %}</h1>
{% endblock %}

{% block main_body %}
    {% if user.is_authenticated and perms.blog.add_blogtag %}
        {% url "blog_tag_create" as tag_create %}
        {% blocktrans %}
            <p>
                <a href="{{ tag_create }}"><button type="button" class="btn btn-success">Create Tag</button></a>.
            </p>
        {% endblocktrans %}
    {% endif %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">{% trans "Owner" %}</th>
                <th scope="col">{% trans "Name" %}</th>
                {% if user.is_authenticated and perms.blog.change_blogpage %}
                    <th scope="col">{% trans "Update" %}</th>
                {% endif %}
                {% if user.is_authenticated and perms.blog.delete_blogpage %}
                    <th scope="col">{% trans "Delete" %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for tag in object_list %}
                <tr>
                    <th scope="row"><a href="{% url "usercp_profile" tag.owner.id %}">{{ tag.owner.username }}</a></th>
                    <td><a href="{% url "blog_article_detail" tag.id tag.slug %}">{{ tag.title }}</a></td>
                    {% if user.is_authenticated and perms.blog.change_blogtag %}
                        <td><a href="{% url "blog_tag_update" tag.id %}"><button type="button" class="btn btn-info">{% trans "Update" %}</button></a></td>
                    {% endif %}
                    {% if user.is_authenticated and perms.blog.delete_blogpost %}
                        <td><a href="{% url "blog_tag_delete" tag.id %}"><button type="button" class="btn btn-danger">{% trans "Delete" %}</button></a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}